# Generated by Django 4.1.4 on 2022-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=10)),
                ('pub_date', models.DateField(default='')),
                ('price', models.IntegerField(default=0)),
                ('subcategory', models.CharField(default='', max_length=40)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
